In [74]:
import pandas as pd
import numpy as np
import keras

In [31]:
df = pd.read_csv("Churn_Modelling.csv")

In [32]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

### Data Pre Processing

In [50]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [51]:
X[:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [52]:
X.shape

(10000, 10)

In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [54]:
ct = ColumnTransformer([("encoder", OneHotEncoder(), [1, 2])], remainder = "passthrough")

In [55]:
X = ct.fit_transform(X)

In [56]:
X.shape

(10000, 13)

In [57]:
X[:5]

array([[1.0, 0.0, 0.0, 1.0, 0.0, 619, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 1.0, 0.0, 608, 41, 1, 83807.86, 1, 0, 1,
        112542.58],
       [1.0, 0.0, 0.0, 1.0, 0.0, 502, 42, 8, 159660.8, 3, 1, 0,
        113931.57],
       [1.0, 0.0, 0.0, 1.0, 0.0, 699, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 1.0, 0.0, 850, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [58]:
from sklearn.model_selection import train_test_split

In [67]:
X= X[:, 1:] # to remove the dummy variable trap

In [60]:
X.shape

(10000, 12)

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [65]:
X_train.shape

(8000, 12)

In [66]:
y_train.shape

(8000,)

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
sc = StandardScaler() 

In [70]:
X_train = sc.fit_transform(X_train)

C:\Users\jaide\Anaconda3\envs\MLAI\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\jaide\Anaconda3\envs\MLAI\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [71]:
X_test = sc.transform(X_test)

C:\Users\jaide\Anaconda3\envs\MLAI\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [73]:
X_train[:5]

array([[-0.5698444 ,  1.74309049,  1.09168714, -1.09168714,  0.16958176,
        -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -0.91601335,  0.91601335, -2.30455945,
         0.30102557, -1.37744033, -0.00631193, -0.92159124,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368,  1.09168714, -1.09168714, -1.19119591,
        -0.94312892, -1.031415  ,  0.57993469, -0.92159124,  0.64259497,
        -1.03227043,  1.48533467],
       [-0.5698444 ,  1.74309049, -0.91601335,  0.91601335,  0.03556578,
         0.10961719,  0.00666099,  0.47312769, -0.92159124,  0.64259497,
        -1.03227043,  1.27652776],
       [-0.5698444 ,  1.74309049,  1.09168714, -1.09168714,  2.05611444,
         1.73658844,  1.04473698,  0.8101927 ,  0.8095029 ,  0.64259497,
         0.9687384 ,  0.55837842]])

### Making the ANN Model

In [88]:
from keras.models import Sequential
from keras.layers import Dense

In [95]:
model = Sequential()

In [96]:
model.add(Dense(100, input_dim = 12, activation = "relu"))

In [97]:
model.add(Dense(500, activation = "relu"))

In [98]:
model.add(Dense(1, activation = "sigmoid"))

In [99]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
"""Adam is the stochastic gradient descent optimizer
that will be used to update the weights"""

'Adam is the stochastic gradient descent optimizer\nthat will be used to update the weights'

In [100]:
model.fit(X_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
8000/8000 [==============================] - 6s 787us/step - loss: 0.3947 - acc: 0.8375
Epoch 2/50
8000/8000 [==============================] - 5s 567us/step - loss: 0.3539 - acc: 0.8535
Epoch 3/50
8000/8000 [==============================] - 4s 546us/step - loss: 0.3435 - acc: 0.8586
Epoch 4/50
8000/8000 [==============================] - 4s 528us/step - loss: 0.3377 - acc: 0.8611
Epoch 5/50
8000/8000 [==============================] - 4s 521us/step - loss: 0.3317 - acc: 0.8632
Epoch 6/50
8000/8000 [==============================] - 4s 499us/step - loss: 0.3284 - acc: 0.8670
Epoch 7/50
8000/8000 [==============================] - 4s 540us/step - loss: 0.3240 - acc: 0.8656
Epoch 8/50
8000/8000 [==============================] - 4s 520us/step - loss: 0.3205 - acc: 0.8691
Epoch 9/50
8000/8000 [==============================] - 4s 540us/step - loss: 0.3176 - acc: 0.8697
Epoch 10/50
8000/8000 [==============================] - 4s 550us/step - loss: 0.3140 - acc: 0.8700
Epoch 11/

In [111]:
y_pred = model.predict(X_test)

In [112]:
y_pred = y_pred > 0.5

In [113]:
y_pred[:5]

array([[ True],
       [False],
       [False],
       [False],
       [False]])

In [115]:
from sklearn.metrics import confusion_matrix
import seaborn as sns

In [116]:
cm = confusion_matrix(y_test, y_pred)

In [120]:
cm

array([[1427,  168],
       [ 178,  227]], dtype=int64)